### ISSUE TITLE
Failing to load node-oauth

### ISSUE THREAD

**Issue by frankcash** [p-m-p/node-fitbit#8]
I'm trying to install this package and get this error

```
Charless-MacBook-Air% npm install fitbit
npm WARN package.json obsidian@0.0.3 No description
npm WARN package.json obsidian@0.0.3 No README data
npm http GET https://registry.npmjs.org/fitbit
npm http 304 https://registry.npmjs.org/fitbit
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
npm ERR! git clone git://github.com/p-m-p/node-oauth Cloning into bare repository '/Users/majora/.npm/_git-remotes/git-github-com-p-m-p-node-oauth-efba15d2'...
npm ERR! git clone git://github.com/p-m-p/node-oauth fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/p-m-p/node-oauth github.com[0: 192.30.252.130]: errno=Operation timed out
npm ERR! Error: Command failed: Cloning into bare repository '/Users/majora/.npm/_git-remotes/git-github-com-p-m-p-node-oauth-efba15d2'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Operation timed out
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:753:16)
npm ERR!     at Socket.<anonymous> (child_process.js:966:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "/usr/local/opt/nvm/v0.10.28/bin/node" "/usr/local/opt/nvm/v0.10.28/bin/npm" "install" "fitbit"
npm ERR! cwd /Users/majora/Code/GetSomeSleep
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/majora/Code/GetSomeSleep/npm-debug.log
npm ERR! not ok code 0
```

I noticed you are using a custom fork of OAuth, is this necessary?

**Comment by frankcash** [comment]
Here is the `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/opt/nvm/v0.10.28/bin/node',
1 verbose cli   '/usr/local/opt/nvm/v0.10.28/bin/npm',
1 verbose cli   'install',
1 verbose cli   'fitbit' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink /usr/local/opt/nvm/v0.10.28/bin/node
5 warn package.json obsidian@0.0.3 No description
6 warn package.json obsidian@0.0.3 No README data
7 verbose readDependencies using package.json deps
8 verbose cache add [ 'fitbit@*', null ]
9 verbose cache add name=undefined spec="fitbit@*" args=["fitbit@*",null]
10 verbose parsed url { protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: 'fitbit@*',
10 verbose parsed url   path: 'fitbit@*',
10 verbose parsed url   href: 'fitbit@*' }
11 verbose cache add name="fitbit" spec="*" args=["fitbit","*"]
12 verbose parsed url { protocol: null,
12 verbose parsed url   slashes: null,
12 verbose parsed url   auth: null,
12 verbose parsed url   host: null,
12 verbose parsed url   port: null,
12 verbose parsed url   hostname: null,
12 verbose parsed url   hash: null,
12 verbose parsed url   search: null,
12 verbose parsed url   query: null,
12 verbose parsed url   pathname: '*',
12 verbose parsed url   path: '*',
12 verbose parsed url   href: '*' }
13 verbose addNamed [ 'fitbit', '*' ]
14 verbose addNamed [ null, '*' ]
15 silly lockFile 844b8a43-fitbit fitbit@*
16 verbose lock fitbit@* /Users/majora/.npm/844b8a43-fitbit.lock
17 silly addNameRange { name: 'fitbit', range: '*', hasData: false }
18 verbose url raw fitbit
19 verbose url resolving [ 'https://registry.npmjs.org/', './fitbit' ]
20 verbose url resolved https://registry.npmjs.org/fitbit
21 info trying registry request attempt 1 at 13:20:36
22 verbose etag "4NM3ZAYBM650JFYIC0IY9NFT9"
23 http GET https://registry.npmjs.org/fitbit
24 http 304 https://registry.npmjs.org/fitbit
25 silly registry.get cb [ 304,
25 silly registry.get   { date: 'Sat, 21 Feb 2015 18:20:35 GMT',
25 silly registry.get     server: 'Apache',
25 silly registry.get     via: '1.1 varnish',
25 silly registry.get     'last-modified': 'Sat, 21 Feb 2015 18:20:35 GMT',
25 silly registry.get     'cache-control': 'max-age=60',
25 silly registry.get     etag: '"4NM3ZAYBM650JFYIC0IY9NFT9"',
25 silly registry.get     age: '0',
25 silly registry.get     'x-served-by': 'cache-atl6225-ATL',
25 silly registry.get     'x-cache': 'MISS',
25 silly registry.get     'x-cache-hits': '0',
25 silly registry.get     'x-timer': 'S1424542835.799083,VS0,VE109',
25 silly registry.get     vary: 'Accept',
25 silly registry.get     'content-length': '0',
25 silly registry.get     'keep-alive': 'timeout=10, max=50',
25 silly registry.get     connection: 'Keep-Alive' } ]
26 verbose etag fitbit from cache
27 silly addNameRange number 2 { name: 'fitbit', range: '*', hasData: true }
28 silly addNameRange versions [ 'fitbit',
28 silly addNameRange   [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '0.0.5', '0.0.6' ] ]
29 verbose addNamed [ 'fitbit', '0.0.6' ]
30 verbose addNamed [ '0.0.6', '0.0.6' ]
31 silly lockFile 105802ae-fitbit-0-0-6 fitbit@0.0.6
32 verbose lock fitbit@0.0.6 /Users/majora/.npm/105802ae-fitbit-0-0-6.lock
33 silly lockFile 105802ae-fitbit-0-0-6 fitbit@0.0.6
34 silly lockFile 105802ae-fitbit-0-0-6 fitbit@0.0.6
35 silly lockFile 844b8a43-fitbit fitbit@*
36 silly lockFile 844b8a43-fitbit fitbit@*
37 silly resolved [ { name: 'fitbit',
37 silly resolved     version: '0.0.6',
37 silly resolved     description: 'Fitbit API client',
37 silly resolved     main: 'lib/fitbit.js',
37 silly resolved     scripts: { test: 'grunt test' },
37 silly resolved     repository: { type: 'git', url: 'git://github.com/p-m-p/node-fitbit.git' },
37 silly resolved     keywords: [ 'fitbit' ],
37 silly resolved     author: { name: 'Phil Parsons' },
37 silly resolved     license: 'MIT',
37 silly resolved     readmeFilename: 'README.md',
37 silly resolved     gitHead: '75eaae79c2d84ef0df1b024f1723c67014fc4bdb',
37 silly resolved     dependencies: { oauth: 'git://github.com/p-m-p/node-oauth', lodash: '~1.3.1' },
37 silly resolved     devDependencies:
37 silly resolved      { grunt: '~0.4.1',
37 silly resolved        'grunt-jasmine-node': '~0.1.0',
37 silly resolved        'grunt-contrib-jshint': '~0.6.0',
37 silly resolved        sinon: '~1.7.3' },
37 silly resolved     readme: 'Fitbit API Client for Node.js [![Build Status](https://travis-ci.org/p-m-p/node-fitbit.png?branch=master)](https://travis-ci.org/p-m-p/node-fitbit)\n===\n\nCurrently a read only implementation for reading data from the Fitbit API\nas an authenticated user.\n\n### TODO\n\nI\'ve split this into two sections, top section is what I need to have for the\nproject I created this module for and the latter is what the API supports.\n\nNeeded by me:\n\n* Add user model\n* Add time series data for models\n* Allow data models to be updated("logged") and deleted via the API\n\nSupported by API:\n\n* Add Blood pressure, heart rate, glucose resource models\n* Add goals for all models that support them\n* Collection metadata models\n* Anything else...\n\n### Installation\n\n`npm install fitbit`\n\n### Usage\n\nBelow is an example usage for authenticating and making a resource request:\n\n```javascript\nvar express = require(\'express\')\n  , config = require(\'./config/app\')\n  , app = express()\n  , Fitbit = require(\'fitbit\');\n\napp.use(express.cookieParser());\napp.use(express.session({secret: \'hekdhthigib\'}));\napp.listen(3000);\n\n// OAuth flow\napp.get(\'/\', function (req, res) {\n  // Create an API client and start authentication via OAuth\n  var client = new Fitbit(config.CONSUMER_KEY, config.CONSUMER_SECRET);\n\n  client.getRequestToken(function (err, token, tokenSecret) {\n    if (err) {\n      // Take action\n      return;\n    }\n\n    req.session.oauth = {\n        requestToken: token\n      , requestTokenSecret: tokenSecret\n    };\n    res.redirect(client.authorizeUrl(token));\n  });\n});\n\n// On return from the authorization\napp.get(\'/oauth_callback\', function (req, res) {\n  var verifier = req.query.oauth_verifier\n    , oauthSettings = req.session.oauth\n    , client = new Fitbit(config.CONSUMER_KEY, config.CONSUMER_SECRET);\n\n  // Request an access token\n  client.getAccessToken(\n      oauthSettings.requestToken\n    , oauthSettings.requestTokenSecret\n    , verifier\n    , function (err, token, secret) {\n        if (err) {\n          // Take action\n          return;\n        }\n\n        oauthSettings.accessToken = token;\n        oauthSettings.accessTokenSecret = secret;\n\n        res.redirect(\'/stats\');\n      }\n  );\n});\n\n// Display some stats\napp.get(\'/stats\', function (req, res) {\n  client = new Fitbit(\n      config.CONSUMER_KEY\n    , config.CONSUMER_SECRET\n    , { // Now set with access tokens\n          accessToken: req.session.oauth.accessToken\n        , accessTokenSecret: req.session.oauth.accessTokenSecret\n        , unitMeasure: \'en_GB\'\n      }\n  );\n\n  // Fetch todays activities\n  client.getActivities(function (err, activities) {\n    if (err) {\n      // Take action\n      return;\n    }\n\n    // `activities` is a Resource model\n    res.send(\'Total steps today: \' + activities.steps());\n  });\n});\n```\n',
37 silly resolved     bugs: { url: 'https://github.com/p-m-p/node-fitbit/issues' },
37 silly resolved     homepage: 'https://github.com/p-m-p/node-fitbit',
37 silly resolved     _id: 'fitbit@0.0.6',
37 silly resolved     _shasum: '7f6b7e1867d4fffae7df3e1e26d7225fb0a0d256',
37 silly resolved     _from: 'fitbit@*',
37 silly resolved     _resolved: 'https://registry.npmjs.org/fitbit/-/fitbit-0.0.6.tgz' } ]
38 info install fitbit@0.0.6 into /Users/majora/Code/GetSomeSleep
39 info installOne fitbit@0.0.6
40 info /Users/majora/Code/GetSomeSleep/node_modules/fitbit unbuild
41 verbose tar unpack /Users/majora/.npm/fitbit/0.0.6/package.tgz
42 silly lockFile a20f271b-GetSomeSleep-node-modules-fitbit tar:///Users/majora/Code/GetSomeSleep/node_modules/fitbit
43 verbose lock tar:///Users/majora/Code/GetSomeSleep/node_modules/fitbit /Users/majora/.npm/a20f271b-GetSomeSleep-node-modules-fitbit.lock
44 silly lockFile 29ad20db-ora-npm-fitbit-0-0-6-package-tgz tar:///Users/majora/.npm/fitbit/0.0.6/package.tgz
45 verbose lock tar:///Users/majora/.npm/fitbit/0.0.6/package.tgz /Users/majora/.npm/29ad20db-ora-npm-fitbit-0-0-6-package-tgz.lock
46 silly gunzTarPerm modes [ '755', '644' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm extractEntry .npmignore
49 silly gunzTarPerm extractEntry README.md
50 silly gunzTarPerm extractEntry Gruntfile.js
51 silly gunzTarPerm extractEntry .travis.yml
52 silly gunzTarPerm extractEntry lib/fitbit.js
53 silly gunzTarPerm extractEntry lib/resources/activities.js
54 silly gunzTarPerm extractEntry lib/resources/body.js
55 silly gunzTarPerm extractEntry lib/resources/devices.js
56 silly gunzTarPerm extractEntry lib/resources/foods.js
57 silly gunzTarPerm extractEntry lib/resources/resource.js
58 silly gunzTarPerm extractEntry lib/resources/sleep.js
59 silly gunzTarPerm extractEntry spec/fitbit-spec.js
60 silly gunzTarPerm extractEntry spec/fixtures.js
61 silly gunzTarPerm extractEntry spec/mocks.js
62 silly gunzTarPerm extractEntry spec/module-loader.js
63 silly gunzTarPerm extractEntry spec/resource-spec.js
64 silly lockFile a20f271b-GetSomeSleep-node-modules-fitbit tar:///Users/majora/Code/GetSomeSleep/node_modules/fitbit
65 silly lockFile a20f271b-GetSomeSleep-node-modules-fitbit tar:///Users/majora/Code/GetSomeSleep/node_modules/fitbit
66 silly lockFile 29ad20db-ora-npm-fitbit-0-0-6-package-tgz tar:///Users/majora/.npm/fitbit/0.0.6/package.tgz
67 silly lockFile 29ad20db-ora-npm-fitbit-0-0-6-package-tgz tar:///Users/majora/.npm/fitbit/0.0.6/package.tgz
68 info preinstall fitbit@0.0.6
69 verbose readDependencies using package.json deps
70 verbose readDependencies using package.json deps
71 verbose cache add [ 'oauth@git://github.com/p-m-p/node-oauth', null ]
72 verbose cache add name=undefined spec="oauth@git://github.com/p-m-p/node-oauth" args=["oauth@git://github.com/p-m-p/node-oauth",null]
73 verbose parsed url { protocol: null,
73 verbose parsed url   slashes: null,
73 verbose parsed url   auth: null,
73 verbose parsed url   host: null,
73 verbose parsed url   port: null,
73 verbose parsed url   hostname: null,
73 verbose parsed url   hash: null,
73 verbose parsed url   search: null,
73 verbose parsed url   query: null,
73 verbose parsed url   pathname: 'oauth@git://github.com/p-m-p/node-oauth',
73 verbose parsed url   path: 'oauth@git://github.com/p-m-p/node-oauth',
73 verbose parsed url   href: 'oauth@git://github.com/p-m-p/node-oauth' }
74 verbose cache add [ 'lodash@~1.3.1', null ]
75 verbose cache add name=undefined spec="lodash@~1.3.1" args=["lodash@~1.3.1",null]
76 verbose parsed url { protocol: null,
76 verbose parsed url   slashes: null,
76 verbose parsed url   auth: null,
76 verbose parsed url   host: null,
76 verbose parsed url   port: null,
76 verbose parsed url   hostname: null,
76 verbose parsed url   hash: null,
76 verbose parsed url   search: null,
76 verbose parsed url   query: null,
76 verbose parsed url   pathname: 'lodash@~1.3.1',
76 verbose parsed url   path: 'lodash@~1.3.1',
76 verbose parsed url   href: 'lodash@~1.3.1' }
77 verbose cache add name="lodash" spec="~1.3.1" args=["lodash","~1.3.1"]
78 verbose parsed url { protocol: null,
78 verbose parsed url   slashes: null,
78 verbose parsed url   auth: null,
78 verbose parsed url   host: null,
78 verbose parsed url   port: null,
78 verbose parsed url   hostname: null,
78 verbose parsed url   hash: null,
78 verbose parsed url   search: null,
78 verbose parsed url   query: null,
78 verbose parsed url   pathname: '~1.3.1',
78 verbose parsed url   path: '~1.3.1',
78 verbose parsed url   href: '~1.3.1' }
79 verbose addNamed [ 'lodash', '~1.3.1' ]
80 verbose addNamed [ null, '>=1.3.1-0 <1.4.0-0' ]
81 silly lockFile dce26891-lodash-1-3-1 lodash@~1.3.1
82 verbose lock lodash@~1.3.1 /Users/majora/.npm/dce26891-lodash-1-3-1.lock
83 verbose cache add name="oauth" spec="git://github.com/p-m-p/node-oauth" args=["oauth","git://github.com/p-m-p/node-oauth"]
84 verbose parsed url { protocol: 'git:',
84 verbose parsed url   slashes: true,
84 verbose parsed url   auth: null,
84 verbose parsed url   host: 'github.com',
84 verbose parsed url   port: null,
84 verbose parsed url   hostname: 'github.com',
84 verbose parsed url   hash: null,
84 verbose parsed url   search: null,
84 verbose parsed url   query: null,
84 verbose parsed url   pathname: '/p-m-p/node-oauth',
84 verbose parsed url   path: '/p-m-p/node-oauth',
84 verbose parsed url   href: 'git://github.com/p-m-p/node-oauth' }
85 silly lockFile efba15d2-git-github-com-p-m-p-node-oauth git://github.com/p-m-p/node-oauth
86 verbose lock git://github.com/p-m-p/node-oauth /Users/majora/.npm/efba15d2-git-github-com-p-m-p-node-oauth.lock
87 silly addNameRange { name: 'lodash', range: '>=1.3.1-0 <1.4.0-0', hasData: false }
88 verbose addRemoteGit [ 'git://github.com/p-m-p/node-oauth', 'master' ]
89 verbose url raw lodash
90 verbose url resolving [ 'https://registry.npmjs.org/', './lodash' ]
91 verbose url resolved https://registry.npmjs.org/lodash
92 info trying registry request attempt 1 at 13:20:37
93 verbose etag "OKEJC1HDEFOXJW85HA35ESMC"
94 http GET https://registry.npmjs.org/lodash
95 http 304 https://registry.npmjs.org/lodash
96 silly registry.get cb [ 304,
96 silly registry.get   { date: 'Sat, 21 Feb 2015 18:20:36 GMT',
96 silly registry.get     server: 'Apache',
96 silly registry.get     via: '1.1 varnish',
96 silly registry.get     'last-modified': 'Sat, 21 Feb 2015 18:20:32 GMT',
96 silly registry.get     'cache-control': 'max-age=60',
96 silly registry.get     etag: '"OKEJC1HDEFOXJW85HA35ESMC"',
96 silly registry.get     age: '19',
96 silly registry.get     'x-served-by': 'cache-atl6222-ATL',
96 silly registry.get     'x-cache': 'HIT',
96 silly registry.get     'x-cache-hits': '2',
96 silly registry.get     'x-timer': 'S1424542836.138638,VS0,VE0',
96 silly registry.get     vary: 'Accept',
96 silly registry.get     'content-length': '0',
96 silly registry.get     'keep-alive': 'timeout=10, max=50',
96 silly registry.get     connection: 'Keep-Alive' } ]
97 verbose etag lodash from cache
98 silly addNameRange number 2 { name: 'lodash', range: '>=1.3.1-0 <1.4.0-0', hasData: true }
99 silly addNameRange versions [ 'lodash',
99 silly addNameRange   [ '0.1.0',
99 silly addNameRange     '0.2.0',
99 silly addNameRange     '0.2.1',
99 silly addNameRange     '0.2.2',
99 silly addNameRange     '0.3.0',
99 silly addNameRange     '0.3.1',
99 silly addNameRange     '0.3.2',
99 silly addNameRange     '0.4.0',
99 silly addNameRange     '0.4.1',
99 silly addNameRange     '0.4.2',
99 silly addNameRange     '0.5.0-rc.1',
99 silly addNameRange     '0.5.0',
99 silly addNameRange     '0.5.1',
99 silly addNameRange     '0.5.2',
99 silly addNameRange     '0.6.0',
99 silly addNameRange     '0.6.1',
99 silly addNameRange     '0.7.0',
99 silly addNameRange     '0.8.0',
99 silly addNameRange     '0.8.1',
99 silly addNameRange     '0.8.2',
99 silly addNameRange     '0.9.0',
99 silly addNameRange     '0.9.1',
99 silly addNameRange     '0.9.2',
99 silly addNameRange     '0.10.0',
99 silly addNameRange     '1.0.0-rc.1',
99 silly addNameRange     '1.0.0-rc.2',
99 silly addNameRange     '1.0.0-rc.3',
99 silly addNameRange     '1.0.0',
99 silly addNameRange     '1.0.1',
99 silly addNameRange     '1.1.0',
99 silly addNameRange     '1.1.1',
99 silly addNameRange     '1.2.0',
99 silly addNameRange     '1.2.1',
99 silly addNameRange     '1.3.0',
99 silly addNameRange     '1.3.1',
99 silly addNameRange     '2.0.0',
99 silly addNameRange     '2.1.0',
99 silly addNameRange     '2.2.0',
99 silly addNameRange     '2.2.1',
99 silly addNameRange     '2.3.0',
99 silly addNameRange     '2.4.0',
99 silly addNameRange     '2.4.1',
99 silly addNameRange     '3.0.0',
99 silly addNameRange     '3.0.1',
99 silly addNameRange     '3.1.0',
99 silly addNameRange     '3.2.0',
99 silly addNameRange     '3.3.0' ] ]
100 verbose addNamed [ 'lodash', '1.3.1' ]
101 verbose addNamed [ '1.3.1', '1.3.1' ]
102 silly lockFile bbff1b50-lodash-1-3-1 lodash@1.3.1
103 verbose lock lodash@1.3.1 /Users/majora/.npm/bbff1b50-lodash-1-3-1.lock
104 silly lockFile bbff1b50-lodash-1-3-1 lodash@1.3.1
105 silly lockFile bbff1b50-lodash-1-3-1 lodash@1.3.1
106 silly lockFile dce26891-lodash-1-3-1 lodash@~1.3.1
107 silly lockFile dce26891-lodash-1-3-1 lodash@~1.3.1
108 error git clone git://github.com/p-m-p/node-oauth Cloning into bare repository '/Users/majora/.npm/_git-remotes/git-github-com-p-m-p-node-oauth-efba15d2'...
108 error git clone git://github.com/p-m-p/node-oauth fatal: unable to connect to github.com:
108 error git clone git://github.com/p-m-p/node-oauth github.com[0: 192.30.252.130]: errno=Operation timed out
109 silly lockFile efba15d2-git-github-com-p-m-p-node-oauth git://github.com/p-m-p/node-oauth
110 silly lockFile efba15d2-git-github-com-p-m-p-node-oauth git://github.com/p-m-p/node-oauth
111 verbose about to build /Users/majora/Code/GetSomeSleep/node_modules/fitbit
112 info /Users/majora/Code/GetSomeSleep/node_modules/fitbit unbuild
113 info preuninstall fitbit@0.0.6
114 info uninstall fitbit@0.0.6
115 verbose true,/Users/majora/Code/GetSomeSleep/node_modules,/Users/majora/Code/GetSomeSleep/node_modules unbuild fitbit@0.0.6
116 info postuninstall fitbit@0.0.6
117 error Error: Command failed: Cloning into bare repository '/Users/majora/.npm/_git-remotes/git-github-com-p-m-p-node-oauth-efba15d2'...
117 error fatal: unable to connect to github.com:
117 error github.com[0: 192.30.252.130]: errno=Operation timed out
117 error
117 error
117 error     at ChildProcess.exithandler (child_process.js:647:15)
117 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
117 error     at maybeClose (child_process.js:753:16)
117 error     at Socket.<anonymous> (child_process.js:966:11)
117 error     at Socket.EventEmitter.emit (events.js:95:17)
117 error     at Pipe.close (net.js:465:12)
118 error If you need help, you may report this *entire* log,
118 error including the npm and node versions, at:
118 error     <http://github.com/npm/npm/issues>
119 error System Darwin 13.3.0
120 error command "/usr/local/opt/nvm/v0.10.28/bin/node" "/usr/local/opt/nvm/v0.10.28/bin/npm" "install" "fitbit"
121 error cwd /Users/majora/Code/GetSomeSleep
122 error node -v v0.10.28
123 error npm -v 1.4.9
124 error code 128
125 verbose exit [ 1, true ]
```

**Comment by frankcash** [comment]
This appears to be a network issue on my end, but is it still necessary to call from a git repo vs NPM?

**Comment by frankcash** [comment]
Yes, can confirm my network is doing something wonky with GitHub, resolves as soon as set the `oauth` dependency to NPM's `*`.

**Comment by p-m-p** [comment]
Yeah I had to fork it originally to add support for custom headers to get the unit types on the API, en_GB and en_US.

**Comment by kevryan2** [comment]
@p-m-p  it looks like you've deleted the fork for the node-oauth and we were actually still using this module in prod so it's breaking new builds, any chance you could put that fork back up or send the changes you'd made so we can fork node-oauth and host it ourselves? thanks!

**Comment by p-m-p** [comment]
> @p-m-p it looks like you've deleted the fork for the node-oauth and we were actually still using this module in prod so it's breaking new builds, any chance you could put that fork back up or send the changes you'd made so we can fork node-oauth and host it ourselves? thanks!

Ah, no sorry I don't have it. I'm surprised I haven't archived this project either as it's not finished or maintained. Feel free to fork it and do what you want but probably worth looking into the security implications of the dependencies.
